version: '3.8'

services:
  app:
    build: .
    container_name: micronaut-app
    ports:
      - "8080:8080"
    environment:
      - DATASOURCES_DEFAULT_URL=jdbc:mysql://db:3306/leilao_eletronico
      - DATASOURCES_DEFAULT_USERNAME=root
      - DATASOURCES_DEFAULT_PASSWORD=admin123
      - FLYWAY_LOCATIONS=classpath:db/migration
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: leilao_eletronico
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
