CREATE TABLE Cliente
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome  VARCHAR(255),
    email VARCHAR(255),
    senha VARCHAR(255),
    CONSTRAINT pk_cliente PRIMARY KEY (id)
);

CREATE TABLE Dispositivo
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    descricao    VARCHAR(255),
    valorInicial DOUBLE PRECISION,
    vendido      BOOLEAN,
    leilao_id    BIGINT,
    nome         VARCHAR(255),
    tipo         VARCHAR(255),
    CONSTRAINT pk_dispositivo PRIMARY KEY (id)
);

CREATE TABLE InstituicaoFinanceira
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome VARCHAR(255),
    cnpj VARCHAR(255),
    CONSTRAINT pk_instituicaofinanceira PRIMARY KEY (id)
);

CREATE TABLE Lance
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    valor      DOUBLE PRECISION,
    cliente_id BIGINT,
    leilao_id  BIGINT,
    CONSTRAINT pk_lance PRIMARY KEY (id)
);

CREATE TABLE Leilao
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dataOcorrencia TIMESTAMP,
    dataVisita     TIMESTAMP,
    endereco       VARCHAR(255),
    cidade         VARCHAR(255),
    estado         VARCHAR(255),
    CONSTRAINT pk_leilao PRIMARY KEY (id)
);

CREATE TABLE Leilao_dispositivos
(
    Leilao_id       BIGINT NOT NULL,
    dispositivos_id BIGINT NOT NULL
);

CREATE TABLE Leilao_veiculos
(
    Leilao_id   BIGINT NOT NULL,
    veiculos_id BIGINT NOT NULL
);

CREATE TABLE Veiculo
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    descricao    VARCHAR(255),
    valorInicial DOUBLE PRECISION,
    vendido      BOOLEAN,
    leilao_id    BIGINT,
    modelo       VARCHAR(255),
    marca        VARCHAR(255),
    tipo         VARCHAR(255),
    CONSTRAINT pk_veiculo PRIMARY KEY (id)
);

CREATE TABLE leilao_instituicao_financeira
(
    instituicao_financeira_id BIGINT NOT NULL,
    leilao_id                 BIGINT NOT NULL
);

ALTER TABLE InstituicaoFinanceira
    ADD CONSTRAINT uc_instituicaofinanceira_cnpj UNIQUE (cnpj);

ALTER TABLE Leilao_dispositivos
    ADD CONSTRAINT uc_leilao_dispositivos_dispositivos UNIQUE (dispositivos_id);

ALTER TABLE Leilao_veiculos
    ADD CONSTRAINT uc_leilao_veiculos_veiculos UNIQUE (veiculos_id);

ALTER TABLE Dispositivo
    ADD CONSTRAINT FK_DISPOSITIVO_ON_LEILAO FOREIGN KEY (leilao_id) REFERENCES Leilao (id);

ALTER TABLE Lance
    ADD CONSTRAINT FK_LANCE_ON_CLIENTE FOREIGN KEY (cliente_id) REFERENCES Cliente (id);

ALTER TABLE Lance
    ADD CONSTRAINT FK_LANCE_ON_LEILAO FOREIGN KEY (leilao_id) REFERENCES Leilao (id);

ALTER TABLE Veiculo
    ADD CONSTRAINT FK_VEICULO_ON_LEILAO FOREIGN KEY (leilao_id) REFERENCES Leilao (id);

ALTER TABLE Leilao_dispositivos
    ADD CONSTRAINT fk_leidis_on_dispositivo FOREIGN KEY (dispositivos_id) REFERENCES Dispositivo (id);

ALTER TABLE Leilao_dispositivos
    ADD CONSTRAINT fk_leidis_on_leilao FOREIGN KEY (Leilao_id) REFERENCES Leilao (id);

ALTER TABLE leilao_instituicao_financeira
    ADD CONSTRAINT fk_leiinsfin_on_instituicao_financeira FOREIGN KEY (instituicao_financeira_id) REFERENCES InstituicaoFinanceira (id);

ALTER TABLE leilao_instituicao_financeira
    ADD CONSTRAINT fk_leiinsfin_on_leilao FOREIGN KEY (leilao_id) REFERENCES Leilao (id);

ALTER TABLE Leilao_veiculos
    ADD CONSTRAINT fk_leivei_on_leilao FOREIGN KEY (Leilao_id) REFERENCES Leilao (id);

ALTER TABLE Leilao_veiculos
    ADD CONSTRAINT fk_leivei_on_veiculo FOREIGN KEY (veiculos_id) REFERENCES Veiculo (id);